---
- name: Créer l'utilisateur système Loki
  user:
    name: loki
    system: yes
    shell: /sbin/nologin

- name: Télécharger le binaire Loki
  get_url:
    url: "https://github.com/grafana/loki/releases/download/v3.0.0/loki-linux-amd64.zip"
    dest: /tmp/loki.zip

- name: Installer unzip
  package:
    name: unzip
    state: present

- name: Décompresser le binaire Loki
  unarchive:
    src: /tmp/loki.zip
    dest: /usr/local/bin
    remote_src: yes
    creates: /usr/local/bin/loki-linux-amd64

- name: Créer les répertoires de configuration et de données
  file:
    path: "{{ item }}"
    state: directory
    owner: loki
    group: loki
    mode: '0755'
  with_items:
    - /etc/loki
    - /tmp/loki
    - /tmp/loki/index
    - /tmp/loki/chunks

- name: Déployer la configuration Loki
  template:
    src: loki-config.yaml.j2
    dest: /etc/loki/loki-config.yaml
    owner: loki
    group: loki
  notify: restart loki

- name: Créer le service systemd pour Loki
  copy:
    dest: /etc/systemd/system/loki.service
    content: |
      [Unit]
      Description=Loki service
      After=network.target

      [Service]
      Type=simple
      User=loki
      ExecStart=/usr/local/bin/loki-linux-amd64 -config.file=/etc/loki/loki-config.yaml
      Restart=on-failure

      [Install]
      WantedBy=multi-user.target
  notify: restart loki

- name: Démarrer et activer le service Loki
  systemd:
    name: loki
    state: started
    enabled: yes
    daemon_reload: yes