---
- name: Créer l'utilisateur système Loki
  user:
    name: loki
    system: yes
    shell: /sbin/nologin

- name: Télécharger et installer Loki
  unarchive:
    src: "https://github.com/grafana/loki/releases/download/v3.0.0/loki-linux-amd64.zip"
    dest: /usr/local/bin
    remote_src: yes
    creates: /usr/local/bin/loki-linux-amd64

- name: Créer les répertoires nécessaires
  file:
    path: "{{ item }}"
    state: directory
    owner: loki
    group: loki
    mode: '0755'
  with_items:
    - /etc/loki
    - /tmp/loki

- name: Déployer la configuration Loki
  template:
    src: loki-config.yaml.j2
    dest: /etc/loki/loki-config.yaml
    owner: loki
    group: loki
  notify: restart loki

- name: Fixer les permissions (Correctif Root)
  file:
    path: /tmp/loki
    state: directory
    owner: loki
    group: loki
    recurse: yes

- name: Créer le service systemd
  copy:
    dest: /etc/systemd/system/loki.service
    content: |
      [Unit]
      Description=Loki service
      After=network.target

      [Service]
      Type=simple
      User=loki
      ExecStart=/usr/local/bin/loki-linux-amd64 -config.file=/etc/loki/loki-config.yaml
      Restart=on-failure

      [Install]
      WantedBy=multi-user.target
  notify: restart loki