---
- name: Installer les dépendances
  apt:
    name: [unzip, curl]
    state: present
    update_cache: yes

- name: Télécharger le binaire Loki v3.0.0
  get_url:
    url: "https://github.com/grafana/loki/releases/download/v3.0.0/loki-linux-amd64.zip"
    dest: "/tmp/loki.zip"

- name: Dézipper Loki
  unarchive:
    src: "/tmp/loki.zip"
    dest: "/usr/local/bin"
    remote_src: yes
    creates: "/usr/local/bin/loki-linux-amd64"

- name: S'assurer que le binaire est exécutable
  file:
    path: /usr/local/bin/loki-linux-amd64
    mode: '0755'

- name: Créer la configuration Loki avec support OTLP
  copy:
    dest: /etc/loki-config.yaml
    content: |
      auth_enabled: false
      server:
        http_listen_port: 3100
      common:
        instance_addr: 127.0.0.1
        path_prefix: /tmp/loki
        storage:
          filesystem:
            chunks_directory: /tmp/loki/chunks
            rules_directory: /tmp/loki/rules
        replication_factor: 1
        ring:
          kvstore:
            store: inmemory
      otlp:
        grpc_listen_address: "0.0.0.0:4317"
        http_listen_address: "0.0.0.0:4318"
      limits_config:
        allow_structured_metadata: true
      schema_config:
        configs:
          - from: 2020-10-24
            store: boltdb-shipper
            object_store: filesystem
            schema: v11
            index:
              prefix: index_
              period: 24h

- name: Créer le service Systemd pour Loki
  copy:
    dest: /etc/systemd/system/loki.service
    content: |
      [Unit]
      Description=Loki Service v3
      After=network.target
      [Service]
      Type=simple
      ExecStart=/usr/local/bin/loki-linux-amd64 -config.file=/etc/loki-config.yaml
      Restart=always
      [Install]
      WantedBy=multi-user.target

- name: Démarrer et activer Loki
  systemd:
    name: loki
    state: restarted
    enabled: yes
    daemon_reload: yes