---
- name: Arrêter Loki
  systemd:
    name: loki
    state: stopped
  ignore_errors: yes

- name: SUPPRIMER les anciennes données (Changement de format de DB requis)
  file:
    path: /tmp/loki
    state: absent

- name: Recréer les répertoires
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0777'
  loop:
    - /tmp/loki
    - /tmp/loki/chunks
    - /tmp/loki/rules

- name: Déployer Config Loki v3 (Compatible OTLP/TSDB)
  copy:
    dest: /etc/loki-config.yaml
    content: |
      auth_enabled: false

      server:
        http_listen_port: 3100
        grpc_listen_port: 9096

      common:
        instance_addr: 127.0.0.1
        path_prefix: /tmp/loki
        storage:
          filesystem:
            chunks_directory: /tmp/loki/chunks
            rules_directory: /tmp/loki/rules
        replication_factor: 1
        ring:
          kvstore:
            store: inmemory

      schema_config:
        configs:
          - from: 2024-01-01
            store: tsdb            # <-- CHANGEMENT ICI (était boltdb-shipper)
            object_store: filesystem
            schema: v13            # <-- CHANGEMENT ICI (était v11)
            index:
              prefix: index_
              period: 24h

      # Cette section est maintenant valide car on est en v13/tsdb
      limits_config:
        allow_structured_metadata: true

- name: Démarrer Loki
  systemd:
    name: loki
    state: restarted
    enabled: yes
    daemon_reload: yes