    - name: Installer Tomcat
      apt:
        name: tomcat9
        state: present

    - name: Installer les outils admin Tomcat
      apt:
        name: tomcat9-admin
        state: present

    - name: S'assurer que Tomcat est démarré
      service:
        name: tomcat9
        state: started
        enabled: yes