- name: Download Tomcat
  get_url:
    url: "https://dlcdn.apache.org/tomcat/tomcat-11/v11.0.15/bin/apache-tomcat-11.0.15.tar.gz"
    dest: /opt/
- name: Extract Tomcat
  unarchive:
    src: /opt/apache-tomcat-11.0.15.tar.gz
    dest: /opt/
    remote_src: yes
- name: Start Tomcat Service
  service:
    name: tomcat
    state: started
    enabled: yes