    - name: Installer Tomcat
      apt:
        name: tomcat10
        state: present

    - name: Installer les outils admin Tomcat
      apt:
        name: tomcat10-admin
        state: present

    - name: S'assurer que Tomcat est démarré
      service:
        name: tomcat10
        state: started
        enabled: yes