- name: Cloner le dépôt Robot Shop
  git:
    repo: 'https://github.com/instana/robot-shop.git'
    dest: /opt/robot-shop
    version: master

- name: Lancer l'application avec Docker Compose
  shell:
    cmd: docker compose -f docker-compose.yaml -f docker-compose-load.yaml up -d
    chdir: /opt/robot-shop