---
- name: Add name to ~/.gitconfig
  community.general.git_config:
    name: user.name
    scope: global
    value: "Poste DEV"

- name: Add email to ~/.gitconfig
  community.general.git_config:
    name: user.email
    scope: global
    value: test@atos.net