- name: Installer Grafana
  ansible.builtin.apt:
    name: grafana
    state: present

- name: Activer et dÃ©marrer Grafana
  ansible.builtin.systemd:
    name: grafana-server
    enabled: true
    state: started
