- name: Installer Node Exporter
  ansible.builtin.apt:
    name: prometheus-node-exporter
    state: present

- name: Activer et d√©marrer Node Exporter
  ansible.builtin.systemd:
    name: prometheus-node-exporter
    enabled: true
    state: started
