---
- name: Activer le dépôt Universe
  ansible.builtin.apt_repository:
    repo: "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe"
    state: present
    update_cache: yes

- name: Installer Node Exporter
  ansible.builtin.apt:
    name: prometheus-node-exporter
    state: present

- name: Activer et démarrer Node Exporter
  ansible.builtin.systemd:
    name: prometheus-node-exporter
    enabled: true
    state: started
